apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::720784121398:role/eksctl-eksctl-demo-nodegroup-ng-9-NodeInstanceRole-1ACMWOMG9U0IX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::720784121398:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-03T11:30:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1594"
  uid: a21351c9-7dbb-44ac-9d93-0eb3294a9ad8
